http://localhost:8080/api/books

###

http://localhost:8080/api/books/6348cb2360bfbbb3b24b6ffc

###

http://localhost:8080/api/books/6348cb2360bfbbb3b24b6fff

###

http://localhost:8080/a

###

DELETE http://localhost:8080/api/books/6348cb2360bfbbb3b24b6ffc

### 末尾のidを一つ変更して、例外を試す

DELETE http://localhost:8080/api/books/6348cb2360bfbbb3b24b6ffe

###

POST http://localhost:8080/api/books
content-type: application/json

{
  "title": "1",
  "description": "2",
  "comment": "3",
  "rating" : 4
}

###

PATCH http://localhost:8080/api/books/63566ef3c58f15f29410dc90
content-type: application/json

{
  "rating" : 2
}
